"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var FTEEmployee_1 = require("./FTEEmployee");
var ContractEmployee_1 = require("./ContractEmployee");
var EmployeeController_1 = require("./EmployeeController");
var Hoa = new FTEEmployee_1.default("Hoa");
var Huyen = new FTEEmployee_1.default("Huyen");
var Thao = new ContractEmployee_1.default("Thao");
var Hanh = new ContractEmployee_1.default("Hanh");
var employeeCtroller = new EmployeeController_1.default();
var employeeList = [Hanh, Hoa, Huyen, Thao];
var total = employeeCtroller.getTotalSalary(employeeList);
console.log("Tong luong la: " + total);
var theBestemployee = employeeCtroller.getBestSalary(employeeList);
console.log("Nhan vien co luong cao nhat la: " + theBestemployee.getName());
var theLowestEm = employeeCtroller.getLowestsalary(employeeList);
console.log("Nhan vien co luong thap nhat la: " + theLowestEm.getName());
employeeCtroller.SortbyASC(employeeList);
employeeCtroller.SortbyDSC(employeeList);
