"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var CheckingAccount_1 = require("./CheckingAccount");
var SavingAccount_1 = require("./SavingAccount");
var savingACC = new SavingAccount_1.default("SavingACC", 1000);
console.log("Thong tin tai khoan BankingAccount: " + savingACC.getBalance());
console.log("Nap tien 100");
savingACC.deposit(100);
console.log("So du trong tai khoan: " + savingACC.getBalance());
console.log("Thuc hien rut tien 100");
savingACC.withdraw(100);
console.log("So du trong tai khoan: " + savingACC.getBalance());
var checkingACC = new CheckingAccount_1.default("CheckingAcc", 50);
console.log("Thong tin tai khoan CheckingAccount: " + checkingACC.getBalance());
console.log("Nap tien 100");
checkingACC.deposit(100);
console.log("So du trong tai khoan: " + checkingACC.getBalance());
console.log("Thuc hien rut tien 110");
checkingACC.withdraw(110);
console.log("So du trong tai khoan : " + checkingACC.getBalance());
